name: ${APP_NAME}

services: 
  frontend:
    image: ${APP_NAME}-frontend:latest
    container_name: frontend
    restart: unless-stopped 
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      # - 7000:7000
      - 24678:24678
    volumes:
      - .:/app:ro
      - frontend-node-modules:/app/node_modules
      - frontend-dist-server:/app/dist-server
      - frontend-dist:/app/dist
      - frontend-logs:/app/logs 
    env_file: 
      - .env 
    environment:
     - RUN_ON_DOCKER=on
     - BACKEND_HOST=backend
     - VITE_MODE=development

volumes:
  frontend-node-modules:
  frontend-dist-server:
  frontend-dist:
  frontend-logs:
      